name: Weekly Achievements Update

on:
  schedule:
    - cron: '0 4 * * 0'  # Runs at 04:00 on Sunday
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-achievements:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Trigger Achievement Update
        env:
          UPDATE_URL: ${{ secrets.ACHIEVEMENT_UPDATE_URL }}
          CRON_TOKEN: ${{ secrets.CRON_SECRET }}
        run: |
          curl -X GET "${UPDATE_URL}" \
          -H "X-Authorization: Bearer ${CRON_TOKEN}"
