name: Weekly Achievements Update

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-achievements:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Trigger Achievement Update
        env:
          UPDATE_URL: ${{ secrets.ACHIEVEMENT_UPDATE_URL }}
          CRON_TOKEN: ${{ secrets.CRON_SECRET }}
        run: |
          echo "Sending request to: ${UPDATE_URL}"
          curl -v -X GET "${UPDATE_URL}" \
          -H "Authorization: Bearer ${CRON_TOKEN}" \
